# Generated by Django 4.2.13 on 2026-06-16 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexte', models.CharField(choices=[('general', 'Général'), ('bsd', 'BSD'), ('recuperateur', 'Récupérateur'), ('operateur', 'Opérateur'), ('stock', 'Stock'), ('agrement', 'Agrément'), ('nomenclature', 'Nomenclature'), ('inspection', 'Inspection'), ('declaration', 'Déclaration'), ('dashboard', 'Tableau de bord')], default='general', max_length=30)),
                ('entite_id', models.PositiveIntegerField(blank=True, help_text="ID de l'entité concernée (BSD, récupérateur, etc.)", null=True)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('loi', 'Loi'), ('decret', 'Décret exécutif'), ('referentiel', 'Référentiel'), ('procedure', 'Procédure'), ('agrement', 'Agrément'), ('nomenclature', 'Nomenclature'), ('glossaire', 'Glossaire'), ('guide', 'Guide'), ('faq', 'FAQ'), ('autre', 'Autre')], max_length=30)),
                ('titre', models.CharField(max_length=300)),
                ('contenu', models.TextField()),
                ('reference_reglementaire', models.CharField(blank=True, help_text='Article, décret, loi concerné', max_length=200)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe')], default='fr', max_length=5)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categorie', 'titre'],
                'indexes': [models.Index(fields=['categorie', 'est_active'], name='ai_assistan_categor_c26e1c_idx'), models.Index(fields=['langue'], name='ai_assistan_langue_74df21_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('bsd_retard', 'BSD en retard'), ('bsd_incomplet', 'BSD incomplet'), ('agrement_expire', 'Agrément expiré'), ('agrement_bientot_expire', 'Agrément bientôt expiré'), ('dechet_non_conforme', 'Déchet non conforme'), ('stock_depasse', 'Stock dépassé'), ('transport_non_autorise', 'Transport non autorisé'), ('traitement_non_conforme', 'Traitement non conforme'), ('document_manquant', 'Document manquant'), ('inspection_requise', 'Inspection requise'), ('nomenclature_erreur', 'Erreur nomenclature'), ('autre', 'Autre')], max_length=40)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('danger', 'Danger'), ('critique', 'Critique')], default='warning', max_length=20)),
                ('description', models.TextField()),
                ('entite_type', models.CharField(blank=True, help_text="Type d'entité concernée (BSD, Agrement, etc.)", max_length=50)),
                ('entite_id', models.PositiveIntegerField(blank=True, null=True)),
                ('lien', models.URLField(blank=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_recommandation', models.CharField(choices=[('verification', 'Vérification'), ('analyse', 'Analyse'), ('alerte', 'Alerte'), ('optimisation', 'Optimisation'), ('formation', 'Formation'), ('correction', 'Correction')], max_length=30)),
                ('recommandation', models.TextField()),
                ('contexte_json', models.JSONField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours de traitement'), ('traitee', 'Traitée'), ('ignoree', 'Ignorée')], default='nouvelle', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'statut', '-date_creation'], name='ai_assistan_utilisa_7d0d60_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant'), ('system', 'Système')], max_length=20)),
                ('message', models.TextField()),
                ('contexte_json', models.JSONField(blank=True, help_text='Contexte de la plateforme associé', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aiconversation')),
            ],
            options={
                'ordering': ['date_creation'],
                'indexes': [models.Index(fields=['conversation', 'date_creation'], name='ai_assistan_convers_c85975_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['utilisateur', '-date_derniere_activite'], name='ai_assistan_utilisa_1ceb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='aialert',
            index=models.Index(fields=['utilisateur', 'est_lue', '-date_creation'], name='ai_assistan_utilisa_3f4309_idx'),
        ),
        migrations.AddIndex(
            model_name='aialert',
            index=models.Index(fields=['type_alerte', 'niveau'], name='ai_assistan_type_al_a4cfce_idx'),
        ),
    ]
