# Generated by Django 4.2.13 on 2026-06-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperateur',
            name='specialisation',
            field=models.TextField(blank=True, default='', help_text='Liste des sous-types de déchets sélectionnés, séparés par des virgules (ex: emb_plastique_pet,sp_huiles)'),
        ),
    ]
