# Generated by Django 4.2.13 on 2026-06-15 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_logo_tenant_nis_alter_tenant_couleur_primaire_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrateur (Plateforme)'), ('ADMIN', 'Administrateur'), ('INSPECTEUR', 'Inspecteur'), ('RECUPERATEUR', 'Recuperateur'), ('READONLY', 'Consultation uniquement')], default='READONLY', max_length=20),
        ),
    ]
