# Generated by Django 4.2.13 on 2026-06-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('registre_commerce', models.CharField(blank=True, max_length=100)),
                ('nif', models.CharField(blank=True, max_length=50)),
                ('wilaya', models.CharField(blank=True, max_length=3)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('plan', models.CharField(choices=[('STARTER', 'Starter - 1 utilisateur'), ('PROFESSIONAL', 'Professional - 5 utilisateurs'), ('ENTERPRISE', 'Enterprise - Illimite')], default='STARTER', max_length=20)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXPIRE', 'Expire'), ('ESSAI', 'Periode essai')], default='ESSAI', max_length=15)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('max_users', models.IntegerField(default=1)),
                ('couleur_primaire', models.CharField(default='#4F46E5', max_length=7)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
