# Generated by Django 4.2.13 on 2026-06-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='nis',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='couleur_primaire',
            field=models.CharField(default='#4F46E5', help_text='Couleur principale ex: #4F46E5', max_length=7),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nom',
            field=models.CharField(max_length=300, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('STARTER', 'Starter — 1 utilisateur'), ('PROFESSIONAL', 'Professional — 5 utilisateurs'), ('ENTERPRISE', 'Enterprise — Illimité')], default='STARTER', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(help_text='Identifiant unique ex: sarl-ecorecup', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXPIRE', 'Expiré'), ('ESSAI', "Période d'essai")], default='ESSAI', max_length=15),
        ),
    ]
