# Generated by Django 4.2.13 on 2026-06-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recuperateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('MENSUELLE', 'Mensuelle'), ('TRIMESTRIELLE', 'Trimestrielle'), ('ANNUELLE', 'Annuelle')], max_length=15)),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField(blank=True, null=True)),
                ('trimestre', models.IntegerField(blank=True, null=True)),
                ('qte_recuperee', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qte_stockee', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qte_transferee', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qte_valorisee', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qte_eliminee', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='BROUILLON', max_length=15)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recuperateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='recuperateurs.recuperateur')),
            ],
            options={
                'ordering': ['-annee', '-created_at'],
            },
        ),
    ]
